### ISSUE TITLE
导航栏菜单问题解答

### ISSUE THREAD

**Issue by twhy** [cdhqing/cdhqing.github.io#2]
第 42 行修改下 https://github.com/cdhqing/cdhqing.github.io/blob/master/lesson6/styles/style.css#L42
```css
nav .navmenu > li:hover > a, .navmenu .nav-sub li:hover > a {
    background-color:#8B50A4;
    font-size: 20px;
}
```
